version: '3.3'

services:
  ubuntu1:
    image: ubuntu
    container_name: ubuntu1
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y openssh-server && echo 'root:root' | chpasswd && service ssh start && sleep infinity"]
    networks:
      - network1
    ports:
      - "2222:22"
    extra_hosts:
      - "host.docker.internal:host-gateway"  

  ubuntu2:
    image: ubuntu
    container_name: ubuntu2
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y openssh-server && echo 'root:root' | chpasswd && service ssh start && sleep infinity"]
    networks:
      - network2
    ports:
      - "2223:22"
    extra_hosts:
      - "host.docker.internal:host-gateway"  

networks:
  network1:
    driver: bridge

  network2:
    driver: bridge
