version: '3'

services:
  web:
    image: nginx
    deploy:
      replicas: 2
    networks:
      - my_overlay

  db:
    image: postgres
    deploy:
      replicas: 2
    networks:
      - my_overlay

networks:
  my_overlay:
    driver: overlay

