version: '1'

services:
  flask-app:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    networks:
      - app-network
    container_name: flask-app
    depends_on:
      - redis

  redis:
    image: redis:latest
    networks:
      - app-network
    container_name: redis

  nginx-static:
    build:
      context: ./nginx-static
      dockerfile: Dockerfile
    networks:
      - app-network
    container_name: nginx-static

  nginx-proxy:
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    container_name: nginx-proxy
    depends_on:
      - flask-app
      - nginx-static

networks:
  app-network:
    driver: bridge